#!/usr/bin/env bash
set -ue

(cd util; cargo check)
(cd util; cargo clippy)

years=$(ls correct)
if [ -z "$years" ]; then
	exit 2
fi

for year in $years; do
	for day in $(seq -f '%02g' 25); do
		correct="correct/${year}/${day}.txt"
		module="aoc/src/y${year}/d${day}"
		if [ -f "$correct" -a -d "$module" ]; then
			output=$(cd util; cargo run --quiet --release $year $day)
			expect=$(cat "$correct")
			echo
			echo "$year $day"
			echo "output: $output"
			echo "expect: $expect"
			if [ "$output" != "$expect" ]; then
				exit 1
			fi
		fi
	done
done
